version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '9001:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_MULTIPLE_DATABASES=test